export const PETS = [
  {
    _id: 1,
    name: 'Veljko-Debeljko',
    category: 1,
    breed: 'Evropska kratkodlaka macka',
    age: '8',
    imageUrl: 'assets/img/veljko-debeljko.jpg',
    dateOfCreation: '2017-07-03T06:33:30.722Z',
    hobbies: [
      'Grickanje kutija',
      'Gledanje kroz prozor',
      'Suncanje stomaka',
      'Sedenje iza kreveta',
      'Gledanje snimaka sa pticama na youtube-u',
      'Boks, slobodni sparing sa Lazom-mazom',
    ],
    gender: 'f',
  },
  {
    _id: 2,
    name: 'Laza-maza',
    category: 1,
    breed: 'Evropska kratkodlaka macka',
    age: '9',
    imageUrl: 'assets/img/laza-maza.jpg',
    dateOfCreation: '2017-05-02T12:15:30.722Z',
    hobbies: [
      'Mazenje',
      'Vijanje loptice',
      'Setnja ispred monitora',
      'Prosnja ljudske hrane koju ne smem da jedem',
      'Grickanje mreznih kablova',
      'Boks, slobodni sparing sa Veljkom-debeljkom',
    ],
    gender: 'f',
  },
  {
    _id: 3,
    name: 'Minimaca',
    category: 1,
    breed: 'Evropska kratkodlaka macka',
    age: '6',
    imageUrl: 'assets/img/minimaca.jpg',
    dateOfCreation: '2016-03-15T21:30:30.722Z',
    hobbies: [
      'Mazenje',
      'Vijanje crvene tackice i pertli',
      'Izigravanje kineza',
      'Dremanje ispred monitora',
      'Pricanje pricica ljudima',
    ],
    gender: 'f',
  },
  {
    _id: 4,
    name: 'Princeza Grejs',
    category: 1,
    breed: 'Kartuzijanska macka',
    age: '6',
    imageUrl: 'assets/img/grejs.jpg',
    dateOfCreation: '2016-10-10T19:25:30.722Z',
    hobbies: [
      'Vijanje crvene tackice',
      'Odrzavanje reda i zakona medju ostalim mackama',
      'Gledanje kroz prozor',
    ],
    gender: 'f',
  },
  {
    _id: 5,
    name: 'Ris',
    category: 1,
    breed: 'Maine Coon',
    age: '2',
    imageUrl: 'assets/img/ris.jpg',
    dateOfCreation: '2016-12-15T17:13:30.722Z',
    hobbies: [
      'Cetkanje i cetkanje i jos cetkanja',
      'Spavanje na hladnim plocicama',
      'Cuvanje dvorista',
    ],
    gender: 'm',
  },
  {
    _id: 6,
    name: 'Boban',
    category: 1,
    breed: 'Miks kartuzijanke i turske angore',
    age: '5',
    imageUrl: 'assets/img/boban.jpg',
    dateOfCreation: '2016-12-15T17:13:30.722Z',
    hobbies: [
      'Zbunjena kontemplacija sveta',
      'Zbunjeno vijanje crvene tacke',
      'Zbunjeno druzenje sa komsijskim mackama',
      'Lezanje na zelenim jastucicima u basti',
      'Cerupanje Flekicinog repa',
    ],
    gender: 'm',
  },
  {
    _id: 7,
    name: 'Flekica',
    category: 1,
    breed: 'Miks kartuzijanke i turske angore',
    age: '5',
    imageUrl: 'assets/img/flekica.jpg',
    dateOfCreation: '2016-12-15T18:13:30.722Z',
    hobbies: [
      'Rvanje sa Bobanom',
      'Vijanje nogu pod pokrivacem, surovo i bez kompromisa',
      'Izigravanje dvoglave macke sa Bobanom',
    ],
    gender: 'f',
  },
  {
    _id: 8,
    name: 'Pufna-fufna',
    category: 2,
    breed: 'Pomeranac',
    age: '0',
    imageUrl: 'assets/img/pufna-fufna.jpg',
    dateOfCreation: '2017-03-07T18:00:30.722Z',
    hobbies: ['Mazenje', 'Kotrljanje', 'Kevtanje'],
    gender: 'm',
  },
  {
    _id: 9,
    name: 'Vuk',
    category: 2,
    breed: 'Bigl',
    age: '3',
    imageUrl: 'assets/img/vuk.jpg',
    dateOfCreation: '2017-03-07T18:00:30.722Z',
    hobbies: [
      'Tenis',
      'Druzenje sa kolegama',
      'Usamljeno lajanje',
      'Lov (uglavnom teniskih loptica)',
    ],
    gender: 'm',
  },
  {
    _id: 10,
    name: 'Blesavko',
    category: 2,
    breed: 'Sibirski haski',
    age: '4',
    imageUrl: 'assets/img/blesavko.jpg',
    dateOfCreation: '2016-11-03T17:45:30.722Z',
    hobbies: ['Stendap komedija', 'Igranje po snegu', 'Pevanje', 'Cetkanje'],
    gender: 'm',
  },
  {
    _id: 11,
    name: 'Akela',
    category: 2,
    breed: 'Labrador',
    age: '5',
    imageUrl: 'assets/img/akela.jpg',
    dateOfCreation: '2017-01-15T11:25:30.722Z',
    hobbies: [
      'Setanje',
      'Kupanje',
      'Kradja i zvakanje papuca',
      'Skakanje u krug',
    ],
    gender: 'm',
  },
  {
    _id: 12,
    name: 'Prasence',
    category: 2,
    breed: 'Mops',
    age: '2',
    imageUrl: 'assets/img/prasence.jpg',
    dateOfCreation: '2016-10-11T10:55:30.722Z',
    hobbies: ['Groktanje', 'Mazenje', 'Komedija'],
    gender: 'f',
  },
  {
    _id: 13,
    name: 'Mica-ptica',
    category: 3,
    breed: 'Africki sivi papagaj',
    age: '1',
    imageUrl: 'assets/img/mica-ptica.jpg',
    dateOfCreation: '2016-08-09T09:25:30.722Z',
    hobbies: ['Front-end developer', 'Gledanje sa visine', 'Kupanje'],
    gender: 'f',
  },
  {
    _id: 14,
    name: 'Sejn',
    category: 3,
    breed: 'Nimfa',
    age: '2',
    imageUrl: 'assets/img/sejn.jpg',
    dateOfCreation: '2015-12-09T23:25:30.722Z',
    hobbies: [
      'Glumac-amater u kaubojskim filmovima',
      'Gledanje vesterna',
      'Bacanje lasa',
    ],
    gender: 'm',
  },
  {
    _id: 15,
    name: 'Gricko',
    category: 4,
    breed: 'Cincila',
    age: '4',
    imageUrl: 'assets/img/gricko.jpg',
    dateOfCreation: '2016-11-07T22:05:30.722Z',
    hobbies: [
      'Grickanje svega i svuda',
      'Napufnjavanje',
      'Cijukanje',
      'Prosenje hrane',
    ],
    gender: 'f',
  },
  {
    _id: 16,
    name: 'Tupko',
    category: 5,
    breed: 'Zlatna ribica',
    age: '1',
    imageUrl: 'assets/img/tupko.jpg',
    dateOfCreation: '2016-12-08T22:05:30.722Z',
    hobbies: [
      'Plivanje levo-desno',
      'Plivanje levo-desno',
      'Plivanje levo-desno',
      'Memorijske igrice',
    ],
    gender: 'f',
  },
  {
    _id: 17,
    name: 'Master Yoda',
    category: 6,
    breed: 'Iguana',
    age: '5',
    imageUrl: 'assets/img/yoda.jpg',
    dateOfCreation: '2017-06-12T21:22:30.722Z',
    hobbies: ['Suncanje', 'Mazenje', 'Prepadanje gostiju'],
    gender: 'm',
  },
  {
    _id: 18,
    name: 'Srecko',
    category: 2,
    breed: 'Mesanac',
    age: '10',
    imageUrl: 'assets/img/srecko.jpg',
    dateOfCreation: '2017-03-10T11:15:30.722Z',
    hobbies: [
      'Mazenje. Puno mazenja',
      'Molba prolaznika za mazenjem',
      'Cviljenje radi mazenja',
    ],
    gender: 'm',
  },
  {
    _id: 19,
    name: 'Kastar',
    category: 1,
    breed: 'Evropska kratkodlaka macka',
    age: '8',
    dateOfCreation: '2017-01-03T06:33:30.722Z',
    hobbies: ['Grdi druge mace', 'Optimizuje poslovanje', 'Resava misiju'],
    gender: 'm',
  },
  {
    name: 'Karton',
    category: 1,
    breed: 'Siamska',
    age: '3',
    hobbies: ['Vijanje miseva', 'Ostavljanje dlaka svuda', 'Grebanje tepiha'],
    gender: 'm',
    _id: 20,
    dateOfCreation: '2017-07-04T09:48:51.751Z',
  },
];
